notifications:
  email:
    false

sudo: false

language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - "pip install ."
  - "pip install coveralls"

script:
  - coverage run --source=vipaccess setup.py test

after_success:
  - coveralls

deploy:
  provider: pypi
  user: moxfyre
  password:
    secure: tupb/NhdRSnNRuEid1+Mjlbf08FbEZb3g04uFzs+OdwCw3NCE70T/fXNmGdFhTyqYFfPt/IcDD3QnZ/aFRKQWMIMFzJj/KKhtxCZpH5QiZBH+oTYwZyyYJ8efP/bLRfRX9PFOt5QqufBlrIF9oZte/d/5C9Qis+H+Ta4bbmhJGcCiJW5XBjtPR2NchCUZB3Kp6zfc0oHC0EZfvfnG5J+O+HIouYIK1ZKv6+WwmQIV3I9ZC212vFTyVRQMglubhiqUVNO/Eay/JmbVjTDEU6oI0vcZA7rqLw78p0COCn4cpEj+ptq4NmRGerg6V3eTkwYs+RIFXuSCcbir1YxrDELmonf4hojwKXvgzt55xWDpHIDNEIt+1pAbGHbvrS/smsDO7NK4+oWM0lAQZOVAGwkc0YOqxW56D8z5Z3F9S9RZI0k4DaL4eg16lBy6wWSMXf5XtflaRlHj0P1gErSTcDSd5pwOH/Qmqd6hlwleWNL1V2JQ4D4XdUhA2ftZcAdzjK6nV6yOuAE9gC9/ivrO1bH0a+QpE09o77wfeEwPef4MmmnrEL7P9mAnYgyXyQTt7FbNaYsK6W5g6XhQCwhb4pfHjTpS3MKv2AD9z9IyeYbOShqBywIcBnxsCIdS2kXbccfE+8Xv9kH5KFlt/7w7bXVsNZAchbQ0hURvGDANP/3p5s=
  on:
    tags: true
    repo: dlenski/python-vipaccess
